jobs:
- job: linux_64
  pool:
    vmImage: ubuntu-16.04
  timeoutInMinutes: 240
  strategy:
    maxParallel: 8
    matrix:
      linux_c_compilergcccxx_compilergxxmpimpich:
        CONFIG: linux_c_compilergcccxx_compilergxxmpimpich
      linux_c_compilergcccxx_compilergxxmpiopenmpi:
        CONFIG: linux_c_compilergcccxx_compilergxxmpiopenmpi
      linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich:
        CONFIG: linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpimpich
      linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi:
        CONFIG: linux_c_compilertoolchain_ccxx_compilertoolchain_cxxmpiopenmpi
  steps:
  - script: |
      sudo pip install --upgrade pip
      sudo pip install setuptools shyaml
    displayName: Install dependencies

  - script: .azure-pipelines/run_docker_build.sh
    displayName: Run docker build